FY sampling procedure
luca-fiorito-11/sandy pull request #194
Opened 2022-05-07 12:53 UTC by EnricaBelfiore

Add correlations to independent fission yield covariance matrix:
---

This notebook shows the perturbation process to obtain an Endf-6 file with the perturbed IFY and a visual comparison between the correlation matrices obtained from the prior covariance matrix and the updated one is showed.

2022-05-08 06:47 UTC, luca-fiorito-11 commented
Does this work without merging PR #126 ?

2022-05-18 07:23 UTC, EnricaBelfiore commented
The aim of the last commit is to correct the errors already present in the `develop` branch. The Notebook inserted will work with these corrections. The methods in the PR #126 will be inserted if needed when they will be properly tested in other Notebooks (ongoing)

2022-05-20 08:20 UTC, AitorBengoechea commented
For version control, this should go on the pull request https://github.com/AitorBengoechea/sandy/tree/fy

2022-05-20 08:20 UTC, AitorBengoechea commented
For version control, this should go on the pull request https://github.com/AitorBengoechea/sandy/tree/fy

2022-05-23 11:31 UTC, EnricaBelfiore commented
> For version control, this should go on the pull request https://github.com/AitorBengoechea/sandy/tree/fy

Not really, all the methods used in the notebook are reported in this PR. There is still an error in the implementation of the `sandy.gls.constrained_gls_update()` method which leads to wrong results in some tests used in FY. It will be fixed in another PR.

2022-05-23 21:08 UTC, luca-fiorito-11 requested changes
Can

2022-05-23 21:08 UTC, luca-fiorito-11 commented on sandy/fy.py
> +    def custom_perturbation(self, pert, **kwargs):
this has to be rediscussed

2022-05-23 21:08 UTC, luca-fiorito-11 commented on sandy/fy.py
> +            MAT   MT     ZAM     ZAP           E           FY         DFY
We will need a notebook to check this...and also maybe to clean up the coding

2022-05-23 21:08 UTC, luca-fiorito-11 commented on sandy/fy.py
> +             MAT   MT     ZAM     ZAP           E          FY         DFY
Same...notebook for this, but in another PR

2022-05-23 21:08 UTC, luca-fiorito-11 commented on sandy/fy.py
>          Vx_prior = fy_data.query('MT==454').DFY
this is not Vx_prior...coding to be adjusted later

2022-05-23 21:08 UTC, luca-fiorito-11 commented on sandy/fy.py
> +                      rows=None, threshold=None):
Use of `threshold` to be discussed

2022-05-23 21:08 UTC, luca-fiorito-11 commented on sandy/fy.py
> +    def ishikawa_factor(self, zam, e, S, Vy_extra, threshold=None):
These will come in a different PR

2022-05-23 21:08 UTC, luca-fiorito-11 commented on sandy/fy.py
> +    def gls_update(self, zam, e, S, y_extra=None, Vy_extra=None,
One or two outputs?

2022-11-08 14:31 UTC, luca-fiorito-11 commented
@EnricaBelfiore , is this PR still relevant?

2022-11-08 14:33 UTC, closed without merging