gls_FY
luca-fiorito-11/sandy pull request #213
Opened 2022-05-31 07:49 UTC by EnricaBelfiore

GLS update of fission yields and their related covariance matrix
---

- Added private method `sandy.Fy._gls_parameters_update()` to update IFY with the GLS update technique for a given zam, energy, design sensitivity and extra information
- Added private method `sandy.Fy._gls_cov_update()` to update the prior IFY covariance matrix using the GLS technique
- Added `sandy.Fy.gls_update()` to perform the GLS update of fission yields and their related covariance matrix, according with
 [Generation of fission yield covariances to correct discrepancies in the nuclear data libraries](https://www.sciencedirect.com/science/article/pii/S0306454915005137?via%3Dihub)

2022-05-31 08:04 UTC, EnricaBelfiore commented
The example tests are numerically correct but they will be changed in the next commit to have a physical meaning. 
I think that in the docstring we should specify that the indices/columns of `S`, `y_extra` and `Vy_extra` must be coherent.

2022-06-02 08:02 UTC, luca-fiorito-11 requested changes
Need notebook

2022-06-02 22:44 UTC, EnricaBelfiore commented on sandy/fy.py
> +            y_extra_ = pd.Series(y_extra).reindex(index=S_.index).fillna(0).values
I agree, y_extra and V_extra must be pd.Series and pd.DataFrame and the names of the indeces must be
consistent with the names of the indices of the sensitivity matrix (like in the example tests). I will add it in the docstring

2022-06-02 22:53 UTC, EnricaBelfiore commented on sandy/fy.py
> +        y_extra_ = pd.Series(y_extra).reindex(index=S_.index).fillna(0).values
The inputs of `sandy._gls_parameters_update` should be np.ndarray

2022-11-08 14:27 UTC, luca-fiorito-11 approved these changes

2022-11-08 14:29 UTC, merged