single_processing
luca-fiorito-11/sandy pull request #251
Opened 2023-02-13 08:26 UTC by fdcroce

2023-02-13 09:05 UTC, fdcroce commented
New function for applying perturbation using or not the multiprocessing. Valid only for cross section perturbations.
New function nuclide2latex for converting nuclide string to latex formatting.

2023-02-13 09:21 UTC, luca-fiorito-11 requested changes

2023-02-13 09:21 UTC, luca-fiorito-11 commented on sandy/zam.py
> +    return out
add blank line at the end according to PEP8 (https://peps.python.org/pep-0008/)

2023-02-13 09:21 UTC, luca-fiorito-11 commented on sandy/zam.py
> +    New function added to directly convert nuclides from string to latex
It will not be "new" forever

2023-02-13 09:21 UTC, luca-fiorito-11 commented on sandy/zam.py
> +    format useful for plotting.
remove "useful for plotting"

2023-02-13 09:21 UTC, luca-fiorito-11 commented on sandy/zam.py
> +    out = zam2latex(nuclide2zam(nuclide, atomic_number = atomic_number, sep = sep))
no whitespaces in keyword arguments, according to PEP8

2023-02-13 09:21 UTC, luca-fiorito-11 commented on sandy/zam.py
> +    out = zam2latex(nuclide2zam(nuclide, atomic_number = atomic_number, sep = sep))
I would write it as:
```
def nuclide2latex(nuclide, atomic_number=False, sep=""):
    out = zam2latex(nuclide2zam(*args, **kwargs))
    return out
```

This is not tested.
Also, Parameters and Returns missing in docstring

2023-02-13 09:21 UTC, luca-fiorito-11 commented on sandy/core/endf6.py
> +    def _mp_apply_perturbations_fdc(self, smps, processes,
naming is not consistent

2023-02-13 09:21 UTC, luca-fiorito-11 commented on sandy/core/endf6.py
> +    def _mp_apply_perturbations_fdc(self, smps, processes,
remove this part from the PR. Let's merge the rest and then submit a new PR

2023-02-13 09:21 UTC, luca-fiorito-11 commented on sandy/zam.py
> +    out = zam2latex(nuclide2zam(nuclide, atomic_number = atomic_number, sep = sep))
tests are also missing

2023-02-13 11:00 UTC, fdcroce commented
i removed the function for applying perturbation since not compliant and I modified to nuclide2latex to implement the recommendations.

2023-02-13 20:09 UTC, luca-fiorito-11 approved these changes

2023-02-14 08:48 UTC, fdcroce commented
Fix bugs in the examples.

2023-02-17 10:14 UTC, luca-fiorito-11 commented
@fdcroce , can you resubmit a PR only including `nuclide2latex`? Thanks

2023-02-17 10:14 UTC, closed without merging