Fix meta stables
luca-fiorito-11/sandy pull request #265
Opened 2023-05-03 17:29 UTC by fdcroce

Fix typo error in method njoy.process_neutrons() and implementation of a new test in endf6.get_ace() to check it works correctly.
Edit worker endf6.endf_pendf_worker to take the correct ZA to emply in the name of ace file. generated The previous version was not able to name correctly in case of metastable nuclides.

2023-05-03 19:11 UTC, luca-fiorito-11 requested changes
Two minor comments

2023-05-03 19:11 UTC, luca-fiorito-11 commented on sandy/core/endf6.py
> +    zam = sandy.zam.za2zam(za, meta=meta,method="")
This change is not needed

2023-05-03 19:11 UTC, luca-fiorito-11 commented on sandy/core/endf6.py
> +        ZA = za,
No spaces

2023-05-03 19:12 UTC, luca-fiorito-11 commented
Can you also comment out the failing test? We'll address it later

2023-05-04 07:24 UTC, fdcroce commented on sandy/core/endf6.py
> +    zam = sandy.zam.za2zam(za, meta=meta,method="")
It is. The za retrieved the first part of endf6 file doesn't follow _"nndc"_, then if method za2zam is _"nndc"_ as default  meta information is discarded. This brings to generation of wrong zam.
Maybe better to change notation in _method=False_ consistently with examples in zam module.

2023-05-04 08:40 UTC, luca-fiorito-11 commented on sandy/core/endf6.py
> +    zam = sandy.zam.za2zam(za, meta=meta,method="")
ok, but add a space between "," and "method"

2023-05-04 08:41 UTC, luca-fiorito-11 approved these changes

2023-05-04 09:00 UTC, luca-fiorito-11 approved these changes

2023-05-04 09:00 UTC, merged